import { Link } from 'react-router-dom';

import ItemCount from './ItemCount';

const ListProducts = () => {
	const products = {
		LAUR: [
			{
				_id: '64d85ec0a4286854074d160a',
				name: 'Aceite de Oliva Extra Virgen Gran Mendoza x 500 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 500 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d160f',
				name: 'Aceite Terroir Extra Virgen Altos Limpios Vidrio x 500 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'Vidrio x 500 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d160e',
				name: 'Aceite Terroir Extra Virgen Cruz de Piedra Organico x 250 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 250 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d160d',
				name: 'Aceite Terroir Extra Virgen Cruz de Piedra Organico x 500 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 500 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1612',
				name: 'Aceite de Oliva Extra Virgen Laur x 500 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 500 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1617',
				name: 'Aceite de Oliva Extra Virgen. GRAN LAUR. X 750 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'X 750 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1614',
				name: 'Aceite de Oliva Extra Virgen Laur x 250 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 250 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1618',
				name: 'Aceite de Oliva Extra Virgen Laur Lata Blend de Terroir x 500 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'Blend de Terroir x 500 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d160b',
				name: 'Aceite Terroir Extra Virgen Medrano Vidrio x 500 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'Vidrio x 500 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d161a',
				name: 'Aceite de Oliva Extra Virgen Laur Lata x 1000 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'Lata x 1000 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1616',
				name: 'Aceite de Oliva Extra Virgen Laur Pet x 5000 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'Pet x 5000 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1619',
				name: 'Aceite de Oliva Extra Virgen Laur Lata Orgánico x 500 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'Lata Orgánico x 500 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1615',
				name: 'Aceite de Oliva Extra Virgen Laur Pet x 2000 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'Pet x 2000 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1611',
				name: 'Aceite de Oliva Extra Virgen Laur x 1000 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 1000 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d160c',
				name: 'Aceite Terroir Extra Virgen Medrano Vidrio x 250 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'Vidrio x 250 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1613',
				name: 'Aceite de Oliva Extra Virgen Laur Orgánico x 500 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 500 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1610',
				name: 'Aceite Terroir Extra Virgen Altos Limpios Vidrio x 250 ml.',
				variety: 'Oliva Extra Virgen',
				presentation: 'Vidrio x 250 ml.',
				producer: 'LAUR',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
		],
		Quetec: [
			{
				_id: '64d85ec0a4286854074d1623',
				name: 'Aceite de Oliva Extra Virgen (Quetec) x 500 cc.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 500 cc.',
				producer: 'Quetec',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1625',
				name: 'Aceite de Oliva Extra Virgen (Quetec) x 1000 cc.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 1000 cc.',
				producer: 'Quetec',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1626',
				name: 'Aceite de Oliva Extra Virgen (Quetec) x 5000 cc.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 5000 cc.',
				producer: 'Quetec',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1628',
				name: 'Aceite de Oliva Extra Virgen Premium (Quetec) x 500.',
				variety: 'Oliva Extra Virgen Premium',
				presentation: 'x 500.',
				producer: 'Quetec',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1622',
				name: 'Aceite de Oliva Extra Virgen (Quetec) x 250 cc.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 250 cc.',
				producer: 'Quetec',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
		],
		'Atilio Avena': [
			{
				_id: '64d85ec0a4286854074d1624',
				name: 'Aceite de Oliva Extra Virgen (Atilio Avena) x 500 cc.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 500 cc.',
				producer: 'Atilio Avena',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1629',
				name: 'Aceite de Oliva Extra Virgen Premium (Atilio Avena) x 500 cc.',
				variety: 'Oliva Extra Virgen Premium',
				presentation: 'x 500 cc.',
				producer: 'Atilio Avena',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1627',
				name: 'Aceite de Oliva Extra Virgen (Atilio Avena) x 5000 cc.',
				variety: 'Oliva Extra Virgen',
				presentation: 'x 5000 cc.',
				producer: 'Atilio Avena',
				category: 'aceites-y-acetos',
				subcategory: 'aceite',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
		],
		'Laur Contraviento': [
			{
				_id: '64d85ec0a4286854074d161e',
				name: 'Aceto Contraviento Bag en Box x 2000 ml',
				variety: 'aceto',
				presentation: 'Box x 2000 ml.',
				producer: 'Laur Contraviento',
				category: 'aceites-y-acetos',
				subcategory: 'aceto',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d161f',
				name: 'Aceto Balsámico Millan x 250 ml',
				variety: 'aceto',
				presentation: 'x 250 ml.',
				producer: 'Laur Contraviento',
				category: 'aceites-y-acetos',
				subcategory: 'aceto',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d161b',
				name: 'Aceto Contraviento Vidrio x 500 ml',
				variety: 'aceto',
				presentation: 'Vidrio x 500 ml.',
				producer: 'Laur Contraviento',
				category: 'aceites-y-acetos',
				subcategory: 'aceto',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d161c',
				name: 'Aceto Contraviento Vidrio x 250 ml',
				variety: 'aceto',
				presentation: 'Vidrio x 250 ml.',
				producer: 'Laur Contraviento',
				category: 'aceites-y-acetos',
				subcategory: 'aceto',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1621',
				name: 'Vinagre de Vino Millan x 500 ml',
				variety: 'aceto',
				presentation: 'x 500 ml.',
				producer: 'Laur Contraviento',
				category: 'aceites-y-acetos',
				subcategory: 'vinagre',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d161d',
				name: 'Aceto en Pet x 2000 ml',
				variety: 'aceto',
				presentation: 'Pet x 2000 ml.',
				producer: 'Laur Contraviento',
				category: 'aceites-y-acetos',
				subcategory: 'aceto',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
			{
				_id: '64d85ec0a4286854074d1620',
				name: 'Aceto di Módena IGP x 250 ml',
				variety: 'aceto',
				presentation: 'x 250 ml.',
				producer: 'Laur Contraviento',
				category: 'aceites-y-acetos',
				subcategory: 'aceto',
				price: 5000,
				thumbnails: '',
				status: true,
				__v: 0,
			},
		],
	};
	return (
		<div>
			{Object.keys(products).map(producer => (
				<div key={producer} className="container-list-products">
					<h3 className="title-product">{producer}</h3>
					<div className="list-product">
						{products[producer].map(product => (
							<Link
								to={`/productos/${product.category}/detalle/${product._id}`}
								key={product._id}
								className="card col-md-3"
							>
								<div>
									<img
										src={product.thumbnails}
										alt={product.name}
										className="card-img-top"
									/>
									<div className="card-body">
										<div className="row-table-info">
											<div className="name-product-table col-12">
												{product.name}
											</div>
											<div className="item-table col-12">${product.price}</div>
										</div>
										<ItemCount />
									</div>
								</div>
							</Link>
						))}
					</div>
				</div>
			))}
		</div>
	);
};

export default ListProducts;
